version: "3.9"
services:
  huutokauppa-db:
    image: postgres
    restart: always
    container_name: huutokauppa-db
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cret123

    volumes:
      - ./data/db:/var/lib/postgresql/data

volumes:
  postgres:
